### PR TITLE
Bcm2836 4.4

### PR DESCRIPTION
**Pull request by andreamerello**
Your branch bcm2836-4.4 boots fine here :) but on my RPi2 I got a lot of:
unexpected IRQ trap at vector 00

I investigated this and it turned out that it is due to the local interrupt controller ISR handler being ivoked without any flag set in the ISR register. Current code does not handle correctly this.

In this pull-request I just made the bcm2836 irqchip driver to tolerate this, but I'm unsure if this situation is supposed to ever happen (or at least to happen so often) or if this is symptom of some other bug. 

Maybe it can happen if an IRQ arrives when the ARM core has already cleared it's IRQ status, but we have not handled yet this in one of the two chained IRQ controllers (so that we get the ARM IRQ set again, and the irqchip is going to be cleared).. Or maybe a similar scenario can happen considering the local IRQ controller and the secondary chained IRQ controller..

RFC Please :)

### CODE REVIEW

**Comment by Fantu** [comment]
Hi, sorry for my probably stupid offtopic question, I have very low arm knowledge, I tried bcm2836-4.4 plus cherry-pick of these patches and build following this (changing something for rpi2 based on what I suppose):
http://elinux.org/RPi_Upstream_Kernel_Compilation
but don't rpi2 don't boot, remain at start color image and network is not working.

I suppose I did something wrong or missed, more exactly I did:
```
# test upstream kernel bcm2836
make bcm2835_defconfig # bcm2836_defconfig missed
make menuconfig # enable multiv7 neon smp  (should enable bcm2836, multiprocessor support and neon or I'm wrong?)
make -j `grep -c ^processor /proc/cpuinfo`
cd ..
git clone git://github.com/swarren/u-boot.git --depth=1
cd u-boot
git checkout -b rpi_dev
make rpi_config
make -j `grep -c ^processor /proc/cpuinfo`
cd tools
boot.scr
---------------------------------------
mmc dev 0
setenv fdtfile bcm2836-rpi-2-b.dtb
setenv bootargs earlyprintk console=tty0 console=ttyAMA0 root=/dev/mmcblk0p2 rootwait
fatload mmc 0:1 ${kernel_addr_r} zImage
fatload mmc 0:1 ${fdt_addr_r} ${fdtfile}
bootz ${kernel_addr_r} - ${fdt_addr_r}
---------------------------------------
./mkimage -A arm -O linux -T script -C none -n boot.scr -d boot.scr boot.scr.uimg
mkdir /boot/firmware/backup
mv /boot/firmware/* /boot/firmware/backup
cp start.elf bootcode.bin from https://github.com/raspberrypi/firmware/tree/master/boot and save it to /boot/firmware/
cp u-boot/u-boot.bin /boot/firmware/kernel.img
cp upstream/arch/arm/boot/zImage /boot/firmware/
cp upstream/arch/arm/boot/dts/bcm2836-rpi-2-b.dtb /boot/firmware/
cp u-boot/tools/boot.scr.uimg /boot/firmware/
```
Modules and overlays are missed in this case, right?
config.txt and cmdline.txt are still needed and/or used?
Can someone give me an help to understand what is missed and/or wrong please?
Thanks for any reply and sorry for my bad english

**Comment by anholt** [comment]
I've reviewed your changes and sent them on to the irqchip maintainers.  Thanks!  I've also pushed an updated 2836-4.4 based on all the 2835/6 changes I'm trying to get into 4.5.

**Comment by andreamerello** [comment]
Cool! Thank you!

BTW, Do you finally convinced yourself that a so large amount of IRQs with
no ISR flag are sane?

As I wrote in my pull-request comments, I could imagine a couple of
scenarios for this thing to happen, but I wasn't completely sure yet...
Il 26/dic/2015 23:49, "Eric Anholt" notifications@github.com ha scritto:

**Comment by anholt** [comment]
Apparently in downstream they figured out that we needed an extra memory barrier.  It would be nice to get that patch as well, but you had a s-o-b and a cleaner patch for just the warning suppression, so I went with it.

**Comment by andreamerello** [comment]
Hmm, do they figured out also where ? I tried to figure it out by myself, but without any result. I finally tried to put full mb() everywhere in the irqchip drivers but again with no results.

Then I gave a look to the downstream code; AFAICT reading their ASM code, they also explicitly handle the "no flag" case by ignoring it.

Even more interesting, I hacked the code so that I could keep a counter for this event... and it rises very quickly. 

Apparently there is nearly a fake IRQ for each good one, including IPIs.. (It is really too much, I will recheck my hack.. maybe I did some mistake..).  However if we assume that the counter works, and if we suppose that the problem is due to some kind of IRQ reentering, back-to-back to a real IRQ, then it might be reasonable that with their, probably faster, ASM code they have a lot more (maybe the IRQ is deasserted with delay for some reason).

Here is my hack (on a downstream 3.18-something):
--- a/arch/arm/mach-bcm2709/include/mach/entry-macro.S
+++ b/arch/arm/mach-bcm2709/include/mach/entry-macro.S
@@ -35,7 +35,17 @@
        ldr     \irqstat, = __io_address(ARM_LOCAL_IRQ_PENDING0)        @ local interrupt source
        add     \irqstat, \irqstat, \base, lsl #2
        ldr     \tmp, [\irqstat]
+#hack
+       cmp     \tmp, #0x0
+       bne     1000f
+       ldr     r1, = irq_err_count
+       ldr     r3, [r1]
+       add     r3, #1
+       str     r3, [r1]
+       b       1020f
+#endhack

+1000:
        /\* test for mailbox0 (IPI) interrupt */
        tst     \tmp, #0x10
        beq     1030f

And here there is its result.. The counter is reported in the "Err:" line
pi@raspberrypi:~$ cat /proc/interrupts 
           CPU0       CPU1       CPU2       CPU3  
 20:          0          0          0          0   ARMCTRL  bcm2708_fb dma
 32:      47909          0          0          0   ARMCTRL  dwc_otg, dwc_otg_pcd, dwc_otg_hcd:usb1
 52:          0          0          0          0   ARMCTRL  BCM2708 GPIO catchall handler
 65:         25          0          0          0   ARMCTRL  ARM Mailbox IRQ
 66:          5          0          0          0   ARMCTRL  VCHIQ doorbell
 75:          1          0          0          0   ARMCTRL
 83:        531          0          0          0   ARMCTRL  uart-pl011
 84:      31510          0          0          0   ARMCTRL  mmc0
 96:          0          0          0          0   ARMCTRL  arch_timer
 97:       4573       3768       3144       3083   ARMCTRL  arch_timer
FIQ:              usb_fiq
IPI0:          0          0          0          0  CPU wakeup interrupts
IPI1:          0          0          0          0  Timer broadcast interrupts
IPI2:       2941       3261       3262       3129  Rescheduling interrupts
IPI3:         11         17         11         14  Function call interrupts
IPI4:          1          1          3          0  Single function call interrupts
IPI5:          0          0          0          0  CPU stop interrupts
IPI6:          0          0          0          0  IRQ work interrupts
IPI7:          0          0          0          0  completion interrupts
Err:      92936

**Comment by anholt** [comment]
This commit from rpi-4.4.y (what they're hopefully using for the next kernel update they do)

commit a1363675944d36fa57b97aac328c3816afb314db
Author: Phil Elwell phil@raspberrypi.org
Date:   Fri Dec 4 17:41:50 2015 +0000

```
irq-bcm2836: Prevent spurious interrupts, and trap them early
```

**Comment by andreamerello** [comment]
Hmm.. I see... This is one of the barrier I tried to add in my experiments, without any apparent improvement. They also say the dummy interrupts are still here.. 

The fact that a similar issue seems to be actually there (silenced) also in the downstream original kernel - although I still have to re-check my hack to detect them - is starting to make me suspecting an HW bug..

**Pull request closed without merging**
